-- File: Mux.vhd
-- Generated by MyHDL 0.9.0
-- Date: Sat Jan 21 21:57:11 2017


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity Mux is
    port (
        a: in std_logic;
        b: in std_logic;
        s: in std_logic;
        y: out std_logic
    );
end entity Mux;


architecture MyHDL of Mux is






begin





MUX_LOGIC: process (a, s, b) is
begin
    if (s = '0') then
        y <= a;
    else
        y <= b;
    end if;
end process MUX_LOGIC;

end architecture MyHDL;
